- team: Rebels
  role: admin
  members:
    - username: halain987
      name: Alain Helaili
      email: hansolo@rebels.org
      title: Captain of the Millennium Falcon
      location: Outer Rim Territories
      timezone: CET/CEST
