name: collaborator
description: Repository collaborator management as code
author: helaili

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: user-plus
  color: red

# Define your inputs here.
inputs:
  filename:
    description: The path to the YAML file containing collaborator definitions
    required: false
    default: '.github/collaborators.yml'
  token:
    description: GitHub token with repo administration permissions
    required: true

runs:
  using: node22
  main: dist/index.js
